import Link from 'next/link'
import './globals.css'
import { Control } from './Control';
import { Youtube } from './youtube';

export const metadata = {
  title: 'Bob Friend',
  description: 'Generated by Million Smile',
}

export default async function RootLayout({ children }) {
  // const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'/topics', { cache: 'no-store' });
  // const topics = await resp.json();
  const video = await fetch(process.env.BACKEND_API_URL+'/api/youtube-lists', { cache: 'no-store' });
  const videos = await video.json();
  

  return (
    <html>
      <body>
        <h1><a href='/'>WEB</a></h1>
        {/* <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
          {children}
          <Control/>
          <Youtube/> */}

          {
            <ol>
              {videos.map((video)=>{
                return <li key={video.etag}>{video.snippet.title}</li>
              })}
            </ol>
          }
      </body>
    </html>
  )
}